# Generated by Django 5.2.6 on 2025-11-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
