# Generated by Django 5.2.6 on 2025-11-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
