# Generated by Django 5.2.6 on 2025-11-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_endereco_cidade_endereco_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
