# Generated by Django 5.2.6 on 2025-11-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_pedido_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagarme_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
