# Generated by Django 5.2.6 on 2025-11-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_pedido_data_pagamento_pedido_pagarme_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
