# Generated by Django 5.2.6 on 2025-11-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_pedido_codigo_rastreio_pedido_etiqueta_gerada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete_servico_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
