# Generated by Django 5.2.6 on 2025-12-06 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=3, default=0.3, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('largura', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('comprimento', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='produtos/principal/')),
                ('is_active', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(related_name='produtos', to='products.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('COMPRA', 'Compra de fornecedor'), ('VENDA', 'Venda para cliente')], max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='products.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/galeria/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='products.produto')),
            ],
        ),
    ]
