# Generated by Django 5.2.6 on 2026-01-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='motivo',
            field=models.CharField(choices=[('COMPRA', 'Compra de fornecedor'), ('VENDA', 'Venda para cliente'), ('AJUSTE', 'Ajuste de estoque')], max_length=255),
        ),
    ]
