# Generated by Django 5.2.6 on 2025-10-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(related_name='produtos', to='products.categoria'),
        ),
    ]
