# Generated by Django 5.2.6 on 2025-10-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_produto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
